### ISSUE TITLE
Upgrade node-gyp to v.8.0.0 to prevent deprecation errors

### ISSUE THREAD

**Issue by silkfire** [npm/run-script#25]
**npm/run-script** currently uses an older version of `node-gyp` that in turn has a dependency on the deprecated package `request`. By upgrading to the newly released version 8.0.0 of `node-gyp` (which now uses `fetch` instead), we can get rid of many deprecation messages stemming from any packages dependent on run-script.

**Comment by wraithgar** [comment]
Because our support contract in npm includes `>=10`, we can not update node-gyp to v 8 until we drop v10 support.

node-gyp@8 requires `>= 10.12.0` of nodejs because it uses the recursive flag for mkdir:

https://github.com/nodejs/node-gyp/blob/5f1a06c50f3b0c3d292f64948f85a004cfcc5c87/lib/configure.js#L75

**Comment by hildjj** [comment]
`node-gyp` claims to support node >=10.12.0:

https://github.com/nodejs/node-gyp/blob/161c2353ef5b562f4acfb2fd77608fcbd0800fc0/package.json#L37

Seems like we could file a bug there to remove the use of the recursive flag for mkdir.
