### ISSUE TITLE
[BUG] in package.json scripts on Windows, \n gobbles the rest of the script

### ISSUE THREAD

**Issue by sciepsilon** [npm/run-script#8]
# What / Why
In an npm package.json script on Windows, `\n` gobbles the rest of the command. 

## When
* A package.json script contains `\n`

## Where
* npm scripts declared in package.json

My environment is:
- Windows PowerShell 5.1.18362.752
- npm 6.14.6
- node v12.18.4

### Current Behavior
Everything until the `\n` is executed. Everything after the `\n` is ignored.

### Steps to Reproduce
In `package.json`:
```json
{
  "scripts": {
    "bad": "echo a\nb && echo c"
  }
}
```

In Windows Powershell:
```
npm run bad
```

Output (note that everything except the last line is a reprint of the command, so really the command's output is just "a"):
```

> mypkg@1.0.0 bad C:\My\Location
> echo a
b && echo c

a
```

### Expected Behavior
`\n` is a common sequence when writing scripts for Mac or Linux, so I expect it not to break unrelated parts of the script when running on Windows. `\n` could be treated literally, which is the normal PowerShell behavior, or it could be treated like the empty string, `` `n `` (the Powershell newline sequence), or `n`. 

## Who
* n/a

## References
 * May be a bug in [npm/read-package-json](https://github.com/npm/read-package-json), rather than a bug in `npm/run-script`. I have cross-posted there.

**Comment by nlf** [comment]
this is a tricky one. we've just released 1.8.0 of this package that switches the string quoting and escaping to use [puka](https://gitlab.com/rhendric/puka) however per puka's own documentation there's some weirdness with line breaks in strings:

> I searched for days for a way to quote or escape line breaks in arguments to
cmd.exe, but couldn't find one (regular ^-prepending and quotation marks
don't seem to cut it). If you know of a way that works, please open an
issue to tell me about it! Until
then, any line break characters (\r or \n) in values being interpolated by
sh will cause an error to be thrown on Windows only.

this seems to be the sort of thing that there's not a great consistent resolution for. if puka lands a fix, then we'll get it pulled in there, otherwise i think there isn't much we can do reasonably here.

**Comment by ruyadorno** [comment]
@nlf I wonder if this has been fixed now that we pulled out `puka` from dependencies?

**Comment by wraithgar** [comment]
> @nlf I wonder if this has been fixed now that we pulled out `puka` from dependencies?

This is npm@6

**Comment by ruyadorno** [comment]
ooops

**Comment by wraithgar** [comment]
This appears to have been fixed and [there are tests](https://github.com/npm/run-script/blob/eb6e576efcdd4a14326f43ce7f090f845afb2eeb/test/run-script-pkg.js#L19) that include scripts with `\n` in them that assert that the entirety of the command is passed to child_process.spawn.
